=== melobio/PrimeGen/packages/shared/src/assets/protocol/schemas/7.json
{
  "$id": "opentronsProtocolSchemaV7",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pipetteName": {
      "description": "Name of a pipette. Does not contain info about specific model/version. Should match keys in pipetteNameSpecs.json file",
      "type": "string",
      "enum": [
        "p10_single",
        "p10_multi",
        "p20_single_gen2",
        "p20_multi_gen2",
        "p50_single",
        "p50_multi",
        "p300_single",
        "p300_multi",
        "p300_single_gen2",
        "p300_multi_gen2",
        "p1000_single",
        "p1000_single_gen2",
        "p50_single_flex",
        "p50_multi_flex",
        "p1000_single_flex",
        "p1000_multi_flex",
        "p1000_96"
      ]
    },

    "moduleOnlyParams": {
      "required": ["moduleId"],
      "additionalProperties": false,
      "properties": {
        "moduleId": {
          "type": "string",
          "description": "Unique identifier of module to target. Must be a key from the top level 'modules' object"
        }
      }
    },

    "offset": {
      "description": "x, y, and z component of offset vector in mm",
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },

    "pipetteAccessParams": {
      "required": ["pipetteId", "labwareId", "wellName"],
      "properties": {
        "pipetteId": {
          "type": "string"
        },
        "labwareId": {
          "type": "string"
        },
        "wellName": {
          "type": "string"
        }
      }
    },

    "volumeParams": {
      "required": ["volume"],
      "volume": {
        "type": "number"
      }
    },

    "flowRate": {
      "required": ["flowRate"],
      "properties": {
        "flowRate": {
          "description": "flow rate in ul/sec",
          "type": "number",
          "exclusiveMinimum": 0
        }
      }
    },

    "wellLocation": {
      "properties": {
        "origin": {
          "type": "string",
          "description": "reference location with respect to a well from which to apply an offset if given (e.g. 'bottom' || 'top')"
        },
        "offset": {
          "$ref": "#/definitions/offset",
          "description": "X, Y, Z offset from the specified origin with respect to well"
        }
      }
    },

    "labwareLocation": {
      "oneOf": [
        {
          "required": ["slotName"],
          "properties": {
            "slotName": {
              "description": "Unique string identifier that corresponds to a slot in the referenced deck definition's locations",
              "type": "string"
            }
          }
        },
        {
          "required": ["moduleId"],
          "properties": {
            "moduleId": {
              "description": "Unique identifier of destination module. Must be a key from the top level 'modules' object.",
              "type": "string"
            }
          }
        },
        {
          "const": "offDeck",
          "description": "String literal 'offDeck'. Used to load a labware without placing it on the deck"
        }
      ]
    }
  },

  "type": "object",
  "additionalProperties": false,
  "required": [
    "$otSharedSchema",
    "schemaVersion",
    "metadata",
    "robot",
    "labwareDefinitions",
    "commands"
  ],
  "properties": {
    "$otSharedSchema": {
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension.",
      "enum": ["#/protocol/schemas/7"]
    },

    "schemaVersion": {
      "description": "Schema version of a protocol is a single integer",
      "enum": [7]
    },

    "metadata": {
      "description": "Optional metadata about the protocol",
      "type": "object",

      "properties": {
        "protocolName": {
          "description": "A short, human-readable name for the protocol",
          "type": "string"
        },
        "author": {
          "description": "The author or organization who created the protocol",
          "type": "string"
        },
        "description": {
          "description": "A text description of the protocol.",
          "type": ["string", "null"]
        },

        "created": {
          "description": "UNIX timestamp when this file was created",
          "type": "number"
        },
        "lastModified": {
          "description": "UNIX timestamp when this file was last modified",
          "type": ["number", "null"]
        },

        "category": {
          "description": "Category of protocol (eg, \"Basic Pipetting\")",
          "type": ["string", "null"]
        },
        "subcategory": {
          "description": "Subcategory of protocol (eg, \"Cell Plating\")",
          "type": ["string", "null"]
        },
        "tags": {
          "description": "Tags to be used in searching for this protocol",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },

    "designerApplication": {
      "description": "Optional data & metadata not required to execute the protocol, used by the application that created this protocol",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the application that created the protocol. Should be namespaced under the organization or individual who owns the organization, eg \"opentrons/protocol-designer\"",
          "type": "string"
        },
        "version": {
          "description": "Version of the application that created the protocol",
          "type": "string"
        },
        "data": {
          "description": "Any data used by the application that created this protocol",
          "type": "object"
        }
      }
    },

    "robot": {
      "required": ["model", "deckId"],
      "properties": {
        "model": {
          "description": "Model of the robot this protocol is written for",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        },
        "deckId": {
          "description": "Identifier of physical deck this protocol is written for. This should match a top-level key in shared-data/deck/definitions/3.json",
          "type": "string"
        }
      }
    },

    "labwareDefinitions": {
      "description": "All labware definitions used by labware in this protocol, keyed by a unique identifier (definitionId)",
      "patternProperties": {
        ".+": {
          "$ref": "opentronsLabwareSchemaV2"
        }
      }
    },

    "liquids": {
      "description": "All instances of liquid used in this protocol, keyed by a unique identifier (liquidId)",
      "patternProperties": {
        ".+": {
          "description": "Fields describing a single liquid",
          "type": "object",
          "required": ["displayName", "description"],
          "properties": {
            "displayName": {
              "description": "An human-readable name for this liquid.",
              "type": "string"
            },
            "description": {
              "description": "A description of this liquid.",
              "type": "string"
            },
            "displayColor": {
              "description": "Hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all acceptable.",
              "type": "string"
            }
          }
        }
      }
    },

    "commands": {
      "description": "An array of command objects representing steps to be executed on the robot.",
      "type": "array",
      "items": { "$ref": "opentronsCommandSchemaV7" }
    },

    "commandAnnotations": {
      "type": "array",
      "items": {
        "description": "An optional object of annotations associated with commands.",
        "type": "object",
        "required": ["commandIds", "annotationType"],
        "properties": {
          "commandIds": {
            "description": "An array of command ids that correspond to the targeted grouping of this annotation",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "annotationType": {
            "description": "The type of annotation (e.g. 'transfer', 'initialSetup')",
            "type": "string"
          },
          "params": {
            "description": "The parameters used to create this grouping of atomic commands",
            "type": "object"
          }
        }
      }
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/protocol/fixtures/7/simpleV7.json
{
  "$otSharedSchema": "#/protocol/schemas/7",
  "schemaVersion": 7,
  "metadata": {
    "protocolName": "Simple test protocol",
    "author": "engineering <engineering@opentrons.com>",
    "description": "A short test protocol",
    "created": 1223131231,
    "tags": ["unitTest"]
  },
  "robot": {
    "model": "OT-2 Standard",
    "deckId": "ot2_standard"
  },
  "liquids": {
    "waterId": {
      "displayName": "Water",
      "description": "Liquid H2O",
      "displayColor": "#7332a8"
    }
  },
  "labwareDefinitions": {
    "opentrons/opentrons_1_trash_1100ml_fixed/1": {
      "ordering": [["A1"]],
      "metadata": {
        "displayCategory": "trash",
        "displayVolumeUnits": "mL",
        "displayName": "Opentrons Fixed Trash",
        "tags": []
      },
      "schemaVersion": 2,
      "version": 1,
      "namespace": "opentrons",
      "dimensions": {
        "xDimension": 172.86,
        "yDimension": 165.86,
        "zDimension": 82
      },
      "parameters": {
        "format": "trash",
        "isTiprack": false,
        "loadName": "opentrons_1_trash_1100ml_fixed",
        "isMagneticModuleCompatible": false,
        "quirks": ["fixedTrash", "centerMultichannelOnWells"]
      },
      "wells": {
        "A1": {
          "shape": "rectangular",
          "yDimension": 165.67,
          "xDimension": 107.11,
          "totalLiquidVolume": 1100000,
          "depth": 77,
          "x": 82.84,
          "y": 53.56,
          "z": 5
        }
      },
      "brand": {
        "brand": "Opentrons"
      },
      "groups": [
        {
          "wells": ["A1"],
          "metadata": {}
        }
      ],
      "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
      }
    },
    "opentrons/opentrons_96_tiprack_10ul/1": {
      "ordering": [
        ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"],
        ["A2", "B2", "C2", "D2", "E2", "F2", "G2", "H2"],
        ["A3", "B3", "C3", "D3", "E3", "F3", "G3", "H3"],
        ["A4", "B4", "C4", "D4", "E4", "F4", "G4", "H4"],
        ["A5", "B5", "C5", "D5", "E5", "F5", "G5", "H5"],
        ["A6", "B6", "C6", "D6", "E6", "F6", "G6", "H6"],
        ["A7", "B7", "C7", "D7", "E7", "F7", "G7", "H7"],
        ["A8", "B8", "C8", "D8", "E8", "F8", "G8", "H8"],
        ["A9", "B9", "C9", "D9", "E9", "F9", "G9", "H9"],
        ["A10", "B10", "C10", "D10", "E10", "F10", "G10", "H10"],
        ["A11", "B11", "C11", "D11", "E11", "F11", "G11", "H11"],
        ["A12", "B12", "C12", "D12", "E12", "F12", "G12", "H12"]
      ],
      "brand": {
        "brand": "Opentrons",
        "brandId": [],
        "links": [
          "https://shop.opentrons.com/collections/opentrons-tips/products/opentrons-10ul-tips"
        ]
      },
      "metadata": {
        "displayName": "Opentrons 96 Tip Rack 10 µL",
        "displayCategory": "tipRack",
        "displayVolumeUnits": "µL",
        "tags": []
      },
      "dimensions": {
        "xDimension": 127.76,
        "yDimension": 85.48,
        "zDimension": 64.69
      },
      "wells": {
        "A1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 74.24,
          "z": 25.49
        },
        "B1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 65.24,
          "z": 25.49
        },
        "C1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 56.24,
          "z": 25.49
        },
        "D1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 47.24,
          "z": 25.49
        },
        "E1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 38.24,
          "z": 25.49
        },
        "F1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 29.24,
          "z": 25.49
        },
        "G1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 20.24,
          "z": 25.49
        },
        "H1": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 14.38,
          "y": 11.24,
          "z": 25.49
        },
        "A2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 74.24,
          "z": 25.49
        },
        "B2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 65.24,
          "z": 25.49
        },
        "C2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 56.24,
          "z": 25.49
        },
        "D2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 47.24,
          "z": 25.49
        },
        "E2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 38.24,
          "z": 25.49
        },
        "F2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 29.24,
          "z": 25.49
        },
        "G2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 20.24,
          "z": 25.49
        },
        "H2": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 23.38,
          "y": 11.24,
          "z": 25.49
        },
        "A3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 74.24,
          "z": 25.49
        },
        "B3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 65.24,
          "z": 25.49
        },
        "C3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 56.24,
          "z": 25.49
        },
        "D3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 47.24,
          "z": 25.49
        },
        "E3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 38.24,
          "z": 25.49
        },
        "F3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 29.24,
          "z": 25.49
        },
        "G3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 20.24,
          "z": 25.49
        },
        "H3": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 32.38,
          "y": 11.24,
          "z": 25.49
        },
        "A4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 74.24,
          "z": 25.49
        },
        "B4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 65.24,
          "z": 25.49
        },
        "C4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 56.24,
          "z": 25.49
        },
        "D4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 47.24,
          "z": 25.49
        },
        "E4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 38.24,
          "z": 25.49
        },
        "F4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 29.24,
          "z": 25.49
        },
        "G4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 20.24,
          "z": 25.49
        },
        "H4": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 41.38,
          "y": 11.24,
          "z": 25.49
        },
        "A5": {
          "depth": 39.2,
          "shape": "circular",
          "diameter": 3.27,
          "totalLiquidVolume": 10,
          "x": 50.38,
          "y": 74.24,
