=== melobio/PrimeGen/packages/shared/src/assets/module/schemas/3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "affineTransform": {
      "description": "A 4x4 row-major matrix describing an affine transform to apply to the labwareOffset and calibrationPoint coordinates of the module (in certain circumstances, e.g. per slot)",
      "type": "array",
      "minItems": 4,
      "maxItems": 4,
      "items": {
        "type": "array",
        "minItems": 4,
        "maxItems": 4,
        "items": {
          "type": "number"
        }
      }
    },
    "svgsonNode": {
      "type": "object",
      "description": "An svgson node that corresponds to a single svg tag",
      "properties": {
        "name": {
          "type": "string",
          "description": "Element name, like svg, circle, line…"
        },
        "type": {
          "type": "string",
          "description": "Element type like element, text…"
        },
        "value": {
          "type": "string",
          "description": "Element value, used in text nodes."
        },
        "children": {
          "type": "array",
          "description": "List of element children",
          "items": { "$ref": "#" }
        },
        "attributes": {
          "type": "object",
          "description": "Attributes for the element"
        }
      }
    }
  },
  "description": "Module specification",
  "type": "object",
  "required": [
    "$otSharedSchema",
    "moduleType",
    "model",
    "labwareOffset",
    "cornerOffsetFromSlot",
    "dimensions",
    "calibrationPoint",
    "displayName",
    "quirks",
    "slotTransforms",
    "compatibleWith",
    "twoDimensionalRendering"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/module/schemas/3 is a reference to this schema."
    },
    "moduleType": {
      "enum": [
        "temperatureModuleType",
        "magneticModuleType",
        "thermocyclerModuleType",
        "heaterShakerModuleType",
        "magneticBlockType"
      ],
      "type": "string"
    },
    "model": {
      "type": "string",
      "pattern": "^(temperatureModule|magneticModule|thermocyclerModule|heaterShakerModule|magneticBlock)V[0-9]+$"
    },
    "labwareOffset": { "$ref": "#/definitions/coordinates" },
    "dimensions": {
      "type": "object",
      "required": [
        "bareOverallHeight",
        "overLabwareHeight",
        "xDimension",
        "yDimension"
      ],
      "properties": {
        "bareOverallHeight": { "type": "number" },
        "overLabwareHeight": { "type": "number" },
        "lidHeight": { "type": "number" },
        "xDimension": { "type": "number" },
        "yDimension": { "type": "number" },
        "footprintXDimension": { "type": "number" },
        "footprintYDimension": { "type": "number" },
        "labwareInterfaceXDimension": { "type": "number" },
        "labwareInterfaceYDimension": { "type": "number" }
      }
    },
    "cornerOffsetFromSlot": {
      "$ref": "#/definitions/coordinates",
      "description": "Position of left-front-bottom corner of entire module chassis to slot footprint origin (left-front-bottom)"
    },
    "calibrationPoint": {
      "$ref": "#/definitions/coordinates",
      "description": "A point on the module's interaction plane (where labware is placed) used for calibrating the module. Slated for future use (as of 2022-05-20)."
    },
    "config": {
      "type": "object",
      "description": "Module's hardware-defined constraints",
      "properties": {
        "minPlateTemperature": { "type": "number" },
        "maxPlateTemperature": { "type": "number" },
        "minShakeSpeed": { "type": "number" },
        "maxShakeSpeed": { "type": "number" },
        "maxEngageHeight": { "type": "number" },
        "minTemperature": { "type": "number" },
        "maxTemperature": { "type": "number" },
        "minBlockTemperature": { "type": "number" },
        "maxBlockTemperature": { "type": "number" },
        "minLidTemperature": { "type": "number" },
        "maxLidTemperature": { "type": "number" },
        "minBlockVolume": { "type": "number" },
        "maxBlockVolume": { "type": "number" }
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on a module.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this module."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this module."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    },
    "displayName": { "type": "string" },
    "quirks": {
      "type": "array",
      "description": "List of quirks for a given module",
      "items": {
        "type": "string"
      }
    },
    "slotTransforms": {
      "type": "object",
      "description": "Per-deckmap sets of per-slot transforms, properties should be ids of decks such as \"ot2_standard\". Transforms for a deck not explicitly listed are the identity.",
      "patternProperties": {
        ".*": {
          "type": "object",
          "patternProperties:": {
            "^([1-9]|10|11)$": {
              "type": "object",
              "description": "Holds 2-D affine transforms that should be applied to top level keys plus the special property $image for applying to images images. If any top level key has no corresponding entry, it is an identity transform. If the transform applies to an entity specifying a 3D position, it should be applied only to the x and y.",
              "patternProperties": {
                ".*": {
                  "type": "object",
                  "description": "The keys identify transforms that apply to different sections of the module definition. Most will be top level keys of the module def (for instance, \"labwareOffset\") but there may also be additional meta keys for values that are not in the def",
                  "patternProperties": {
                    ".*": { "$ref": "#/definitions/affineTransform" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "compatibleWith": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "A compatible module model (e.g. temperatureModuleV1)"
      }
    },
    "twoDimensionalRendering": {
      "type": "object",
      "description": "SVG rendering of the module represented as svgson",
      "items": { "$ref": "#/definitions/svgsonNode" }
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/module/definitions/3/temperatureModuleV2.json
{
  "$otSharedSchema": "module/schemas/3",
  "moduleType": "temperatureModuleType",
  "model": "temperatureModuleV2",
  "labwareOffset": {
    "x": -1.45,
    "y": -0.15,
    "z": 80.09
  },
  "dimensions": {
    "bareOverallHeight": 84,
    "overLabwareHeight": 0,
    "xDimension": 196,
    "yDimension": 91,
    "footprintXDimension": 128,
    "footprintYDimension": 86,
    "labwareInterfaceXDimension": 128,
    "labwareInterfaceYDimension": 86
  },
  "cornerOffsetFromSlot": {
    "x": -68.5,
    "y": -1.8,
    "z": 0
  },
  "calibrationPoint": {
    "x": 11.7,
    "y": 8.75,
    "z": 80.09
  },
  "config": {
    "minTemperature": 9,
    "maxTemperature": 99
  },
  "gripperOffsets": {
    "default": {
      "pickUpOffset": {
        "x": 0,
        "y": 0,
        "z": 0
      },
      "dropOffset": {
        "x": 0,
        "y": 0,
        "z": 0.5
      }
    }
  },
  "displayName": "Temperature Module GEN2",
  "quirks": [],
  "slotTransforms": {
    "ot2_standard": {
      "3": {
        "labwareOffset": [
          [-1, 0, 0, -0.3],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      },
      "6": {
        "labwareOffset": [
          [-1, 0, 0, -0.3],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      },
      "9": {
        "labwareOffset": [
          [-1, 0, 0, -0.3],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      }
    },
    "ot2_short_trash": {
      "3": {
        "labwareOffset": [
          [-1, 0, 0, -0.15],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      },
      "6": {
        "labwareOffset": [
          [-1, 0, 0, -0.15],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      },
      "9": {
        "labwareOffset": [
          [-1, 0, 0, -0.15],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]
        ]
      }
    },
    "ot3_standard": {
      "D1": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "C1": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "B1": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "A1": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "D3": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "C3": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      },
      "B3": {
        "labwareOffset": [
          [1, 0, 0, 1.45],
          [0, 1, 0, 0.15],
          [0, 0, 1, -71.09],
          [0, 0, 0, 1]
        ]
      }
    }
  },
  "compatibleWith": ["temperatureModuleV1"],
  "twoDimensionalRendering": {
    "name": "svg",
    "type": "element",
    "value": "",
    "attributes": {
      "version": "1.1",
      "id": "temperatureModule",
      "xmlns": "http://www.w3.org/2000/svg",
      "xmlns:xlink": "http://www.w3.org/1999/xlink",
      "x": "0px",
      "y": "0px",
      "viewBox": "0 0 197.7 88.6",
      "style": "enable-background:new 0 0 197.7 88.6;",
      "xml:space": "preserve"
    },
    "children": [
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "darkFill"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "style": "fill-rule:evenodd;clip-rule:evenodd;fill:#E6E6E6;",
              "d": "M74,89.3c-2.2,0-4.2-1.2-5.3-3H6.1V19.2H0.4V9.6h5.7V3.7h62.6c1.1-1.8,3.1-3,5.3-3h123V45v41.3v3H74z\n\t\t M28.5,39.5c0-1.5-1.2-2.7-2.7-2.7l0,0c-1.5,0-2.7,1.2-2.7,2.7v10.9c0,1.5,1.2,2.7,2.7,2.7s2.7-1.2,2.7-2.7V39.5z M46.3,34.4H32.1\n\t\tv21.2h14.2V34.4L46.3,34.4z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "outline"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M197.7,0H5.3v90h192.4V0z M6.7,1.4h189.6v87.1H6.7V1.4z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "labwareSurface"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M197.7,0H74c-3.8,0-7,3.1-7,7v76c0,3.8,3.1,7,7,7h123.7V0z M74,88.6c-3,0-5.5-2.5-5.5-5.5V7c0-3,2.5-5.5,5.5-5.5h122.3\n\t\tv87.1H74z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "innerWalls"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M6,86.4h62.5v-0.7H6V86.4z M6,4.1h63.4V3.3H6L6,4.1L6,4.1z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "powerButton"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M6.4,9.2H0v10.3h6.4V9.2z M0.7,9.9h5v8.9h-5V9.9z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "displayPanel"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M46.3,34.1H32.1c-0.2,0-0.4,0.2-0.4,0.4v21.2c0,0.2,0.2,0.4,0.4,0.4h14.2c0.2,0,0.4-0.2,0.4-0.4V34.4\n\t\tC46.7,34.2,46.5,34.1,46.3,34.1z M32.5,34.8h13.4v20.4H32.5V34.8z"
            },
            "children": []
          }
        ]
      },
      {
        "name": "g",
        "type": "element",
        "value": "",
        "attributes": {
          "id": "statusLight"
        },
        "children": [
          {
            "name": "path",
            "type": "element",
            "value": "",
            "attributes": {
              "d": "M25.8,36.5c-1.7,0-3.1,1.4-3.1,3.1v10.9c0,1.7,1.4,3.1,3.1,3.1s3.1-1.4,3.1-3.1v-11C28.9,37.8,27.5,36.5,25.8,36.5z\n\t\t M25.8,52.8c-1.3,0-2.4-1.1-2.4-2.4V39.5c0-1.3,1.1-2.4,2.4-2.4c1.3,0,2.4,1.1,2.4,2.4v10.9C28.2,51.8,27.1,52.8,25.8,52.8z"
            },
            "children": []
          }
        ]
      }
    ]
  }
}
