=== melobio/PrimeGen/packages/shared/src/assets/deck/schemas/3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    },
    "unitVector": {
      "type": "array",
      "description": "Array of 3 unit directions, [x, y, z]",
      "items": {
        "type": "number",
        "enum": [1, -1]
      },
      "minItems": 3,
      "maxItems": 3
    },
    "boundingBox": {
      "type": "object",
      "description": "The active area (both pipettes can reach) of a fixture on the deck",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "xDimension": { "$ref": "#/definitions/positiveNumber" },
        "yDimension": { "$ref": "#/definitions/positiveNumber" },
        "zDimension": { "$ref": "#/definitions/positiveNumber" }
      }
    },
    "svgsonNode": {
      "type": "object",
      "description": "An svgson node that corresponds to a single svg tag",
      "properties": {
        "name": {
          "type": "string",
          "description": "Element name, like svg, circle, line…"
        },
        "type": {
          "type": "string",
          "description": "Element type like element, text…"
        },
        "value": {
          "type": "string",
          "description": "Element value, used in text nodes."
        },
        "children": {
          "type": "array",
          "description": "List of element children",
          "items": { "$ref": "#/definitions/svgsonNode" }
        },
        "attributes": {
          "type": "object",
          "description": "Attributes for the element"
        }
      }
    }
  },

  "description": "Deck specifications, where x,y,z (0,0,0) is at front the bottom left corner.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "otId",
    "schemaVersion",
    "cornerOffsetFromOrigin",
    "dimensions",
    "metadata",
    "robot",
    "locations",
    "layers"
  ],
  "properties": {
    "otId": {
      "description": "Unique internal ID generated using UUID",
      "type": "string"
    },
    "schemaVersion": {
      "description": "Schema version of a deck is a single integer",
      "enum": [3]
    },
    "cornerOffsetFromOrigin": {
      "$ref": "#/definitions/xyzArray",
      "description": "Position of left-front-bottom corner of entire deck to robot coordinate system origin"
    },
    "dimensions": {
      "$ref": "#/definitions/xyzArray",
      "description": "Outer dimensions of a deck bounding box"
    },
    "metadata": {
      "description": "Optional metadata about the Deck",
      "type": "object",
      "properties": {
        "displayName": {
          "description": "A short, human-readable name for the deck",
          "type": "string"
        },
        "tags": {
          "description": "Tags to be used in searching for this deck",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "robot": {
      "type": "object",
      "required": ["model"],
      "properties": {
        "model": {
          "description": "Model of the robot",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        }
      }
    },
    "locations": {
      "type": "object",
      "required": ["orderedSlots", "calibrationPoints"],
      "properties": {
        "orderedSlots": {
          "type": "array",
          "description": "Ordered slots available for placing labware",
          "items": {
            "type": "object",
            "required": [
              "id",
              "position",
              "boundingBox",
              "displayName",
              "compatibleModuleTypes"
            ],
            "properties": {
              "id": {
                "description": "Unique identifier for slot",
                "type": "string"
              },
              "position": {
                "$ref": "#/definitions/xyzArray"
              },
              "matingSurfaceUnitVector": {
                "$ref": "#/definitions/unitVector",
                "description": "An optional diagonal direction of force, defined by spring location, which governs the mating surface of objects placed in slot."
              },
              "boundingBox": {
                "$ref": "#/definitions/boundingBox"
              },
              "displayName": {
                "description": "A human-readable nickname for this slot Eg \"Slot 1\" or \"Fixed Trash\"",
                "type": "string"
              },
              "compatibleModuleTypes": {
                "description": "An array of module types that can be placed in this slot.",
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "magneticModuleType",
                    "temperatureModuleType",
                    "thermocyclerModuleType",
                    "heaterShakerModuleType",
                    "magneticBlockType"
                  ]
                }
              }
            }
          }
        },
        "calibrationPoints": {
          "type": "array",
          "description": "Key points for deck calibration",
          "items": {
            "type": "object",
            "required": ["id", "position", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for calibration point",
                "type": "string"
              },
              "position": {
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this point Eg \"Slot 3 Cross\" or \"Slot 1 Dot\"",
                "type": "string"
              }
            }
          }
        },
        "fixtures": {
          "type": "array",
          "description": "Fixed position objects on the deck.",
          "items": {
            "type": "object",
            "required": ["id", "displayName"],
            "properties": {
              "id": {
                "description": "Unique identifier for fixed object",
                "type": "string"
              },
              "labware": {
                "description": "Valid labware loadName for fixed object",
                "type": "string"
              },
              "boundingBox": {
                "$ref": "#/definitions/boundingBox"
              },
              "slot": {
                "description": "Slot location of the fixed object",
                "type": "string"
              },
              "position": {
                "$ref": "#/definitions/xyzArray"
              },
              "displayName": {
                "description": "An optional human-readable nickname for this fixture Eg \"Tall Fixed Trash\" or \"Short Fixed Trash\"",
                "type": "string"
              }
            },
            "oneOf": [
              {
                "anyOf": [
                  {
                    "required": ["labware", "slot"]
                  },
                  {
                    "required": ["labware", "position"]
                  }
                ]
              },
              {
                "anyOf": [
                  {
                    "required": ["boundingBox", "slot"]
                  },
                  {
                    "required": ["boundingBox", "position"]
                  }
                ]
              }
            ]
          }
        }
      }
    },
    "layers": {
      "type": "array",
      "description": "Layered feature groups of the deck.",
      "items": {
        "$ref": "#/definitions/svgsonNode"
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on this deck.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this deck."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this deck."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/deck/definitions/3/ot2_short_trash.json
{
  "otId": "ot2_short_trash",
  "schemaVersion": 3,
  "cornerOffsetFromOrigin": [-115.65, -68.03, 0],
  "dimensions": [624.3, 565.2, 0],
  "metadata": {
    "displayName": "OT-2 Short-Trash Deck",
    "tags": ["ot2", "12 slots", "short trash"]
  },
  "robot": {
    "model": "OT-2 Standard"
  },
  "locations": {
    "orderedSlots": [
      {
        "id": "1",
        "position": [0.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 1",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "2",
        "position": [132.5, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 2",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "3",
        "position": [265.0, 0.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 3",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "4",
        "position": [0.0, 90.5, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 4",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "5",
        "position": [132.5, 90.5, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 5",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "6",
        "position": [265.0, 90.5, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 6",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "7",
        "position": [0.0, 181.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 7",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "thermocyclerModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "8",
        "position": [132.5, 181.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 8",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "9",
        "position": [265.0, 181.0, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 9",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "10",
        "position": [0.0, 271.5, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 10",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "11",
        "position": [132.5, 271.5, 0.0],
        "matingSurfaceUnitVector": [-1, 1, -1],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 11",
        "compatibleModuleTypes": [
          "magneticModuleType",
          "temperatureModuleType",
          "heaterShakerModuleType"
        ]
      },
      {
        "id": "12",
        "position": [265.0, 271.5, 0.0],
        "boundingBox": {
          "xDimension": 128.0,
          "yDimension": 86.0,
          "zDimension": 0
        },
        "displayName": "Slot 12",
        "compatibleModuleTypes": []
      }
    ],
    "calibrationPoints": [
      {
        "id": "1BLC",
        "position": [12.13, 9.0, 0.0],
        "displayName": "Slot 1 Bottom Left Cross"
      },
      {
        "id": "3BRC",
        "position": [380.87, 9.0, 0.0],
        "displayName": "Slot 3 Bottom Right Cross"
      },
      {
        "id": "7TLC",
        "position": [12.13, 258.0, 0.0],
        "displayName": "Slot 7 Top Left Cross"
      },
      {
        "id": "9TRC",
        "position": [380.87, 258.0, 0.0],
        "displayName": "Slot 9 Top Right Cross"
      },
      {
        "id": "10TLC",
        "position": [12.13, 348.5, 0.0],
        "displayName": "Slot 10 Top Left Cross"
      },
      {
        "id": "11TRC",
        "position": [248.37, 348.5, 0.0],
        "displayName": "Slot 11 Top Right Cross"
      },
      {
        "id": "1BLD",
        "position": [12.13, 6.0, 0.0],
        "displayName": "Slot 1 Bottom Left Dot"
      },
      {
        "id": "3BRD",
        "position": [380.87, 6.0, 0.0],
        "displayName": "Slot 3 Bottom Right Dot"
      },
      {
        "id": "7TLD",
        "position": [12.13, 261.0, 0.0],
        "displayName": "Slot 7 Top Left Dot"
      },
      {
        "id": "9TRD",
        "position": [380.87, 261.0, 0.0],
        "displayName": "Slot 9 Top Right Dot"
      },
      {
        "id": "10TLD",
        "position": [12.13, 351.5, 0.0],
        "displayName": "Slot 10 Top Left Dot"
      },
      {
        "id": "11TRD",
        "position": [248.37, 351.5, 0.0],
        "displayName": "Slot 11 Top Right Dot"
      }
    ],
    "fixtures": [
      {
        "id": "fixedTrash",
        "slot": "12",
        "labware": "opentrons_1_trash_850ml_fixed",
        "displayName": "Fixed Trash"
      }
    ]
  },
  "layers": [
    {
      "name": "g",
      "type": "element",
      "value": "",
      "attributes": {
        "id": "fixedBase"
      },
      "children": [
        {
          "name": "path",
          "type": "element",
          "value": "",
          "attributes": {
            "style": "fill:#fff;stroke:#ccc;width:100%;height:100%",
            "d": "M506.326,494.546h-619.653V-65.506h68.503V397c0,2.935,2.388,5.324,5.324,5.324H260c2.935,0,5.324-2.388,5.324-5.324V284.5c0-6.99,5.687-12.676,12.677-12.676h154.5c2.936,0,5.324-2.388,5.324-5.324V-65.506h68.503V494.546z"
          },
          "children": []
        }
      ]
    },
    {
      "name": "g",
      "type": "element",
      "value": "",
      "attributes": {
        "id": "fixedTrash"
      },
      "children": [
        {
          "name": "path",
          "type": "element",
          "value": "",
          "attributes": {
            "style": "fill:#ededed;stroke:none;fill-rule:evenodd;",
            "d": "M441.107,289.57v135.86c0,8.368-6.808,15.176-15.176,15.176H283.07c-8.368,0-15.176-6.808-15.176-15.176V289.57c0-8.368,6.808-15.177,15.176-15.177h142.86C434.298,274.394,441.107,281.202,441.107,289.57z M425.053,434H283.947c-1.24,0-2.484-0.034-3.702-0.287c-2-0.416-3.81-1.446-4.884-3.227c-1.152-1.91-1.289-4.185-1.289-6.359v-88.629c0-2.683,0.259-5.609,2.263-7.612c2.004-2.003,4.928-2.263,7.612-2.263h25.939c1.693,0.006,3.545-0.167,4.807-1.429c1.262-1.262,1.435-3.115,1.429-4.807v-28.94c0-2.124,0.129-4.338,1.209-6.225c1.059-1.851,2.904-2.933,4.954-3.36c1.222-0.255,2.468-0.289,3.712-0.289h99.056c2.124,0,4.339,0.129,6.226,1.209c1.851,1.06,2.933,2.904,3.36,4.954c0.255,1.222,0.289,2.468,0.289,3.712v133.68c0,2.684-0.259,5.607-2.263,7.611C430.661,433.741,427.737,434,425.053,434z"
          },
          "children": []
        }
      ]
    },
    {
      "name": "g",
      "type": "element",
      "value": "",
      "attributes": {
        "id": "doorStops"
      },
      "children": [
        {
          "name": "path",
          "type": "element",
          "value": "",
          "attributes": {
            "style": "fill:#fff;stroke:#ccc;width:100%;height:100%",
            "d": "M-63.6-67.68v2.35h8.06v-2.35H-63.6z M-75.45-65.33h27.95c1.381,0,2.5,1.119,2.5,2.5v15c0,1.381-1.119,2.5-2.5,2.5h-27.95c-1.381,0-2.5-1.119-2.5-2.5v-15C-77.95-64.211-76.831-65.33-75.45-65.33z M468.45-45.33H440.5c-1.381,0-2.5-1.119-2.5-2.5v-15c0-1.381,1.119-2.5,2.5-2.5h27.95c1.381,0,2.5,1.119,2.5,2.5v15C470.95-46.449,469.831-45.33,468.45-45.33z"
          },
          "children": []
        }
      ]
    },
    {
      "name": "g",
      "type": "element",
      "value": "",
      "attributes": {
        "id": "metalFrame"
      },
      "children": [
        {
          "name": "path",
          "type": "element",
          "value": "",
          "attributes": {
