=== melobio/PrimeGen/packages/shared/src/assets/pipette/schemas/2/pipetteGeometrySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    }
  },
  "type": "object",
  "required": ["$otSharedSchema", "nozzleOffset", "pathTo3D"],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteGeometrySchema.json is a reference to this schema."
    },
    "nozzleOffset": { "$ref": "#/definitions/xyzArray" },
    "pathTo3D": {
      "description": "path to the gltf file representing the 3D pipette model",
      "type": "string",
      "pattern": "^pipette/definitions/[2]/geometry/([a-z]*_[a-z]*)+/p[0-9]{2,4}/[a-z]*[.]gltf"
    },
    "nozzleMap": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "patternProperties": {
        "[A-Z]+[0-9]+": { "$ref": "#/definitions/xyzArray" }
      }
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/geometry/eight_channel/p20/2_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "nozzleOffset": [0.0, 31.5, 19.4],
  "pathTo3D": "pipette/definitions/2/geometry/eight_channel/p20/placeholder.gltf",
  "nozzleMap": {
    "A1": [0.0, 31.5, 19.4],
    "B1": [0.0, 40.5, 19.4],
    "C1": [0.0, 49.5, 19.4],
    "D1": [0.0, 58.5, 19.4],
    "E1": [0.0, 67.5, 19.4],
    "F1": [0.0, 76.5, 19.4],
    "G1": [0.0, 85.5, 19.4],
    "H1": [0.0, 94.5, 19.4]
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/geometry/eight_channel/p1000/3_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "pathTo3D": "pipette/definitions/2/geometry/eight_channel/p50/placeholder.gltf",
  "nozzleOffset": [-8.0, -16.0, -259.15],
  "nozzleMap": {
    "A1": [-8.0, -16.0, -259.15],
    "B1": [-8.0, -7.0, -259.15],
    "C1": [-8.0, 2.0, -259.15],
    "D1": [-8.0, 11.0, -259.15],
    "E1": [-8.0, 20.0, -259.15],
    "F1": [-8.0, 29.0, -259.15],
    "G1": [-8.0, 38.0, -259.15],
    "H1": [-8.0, 47.0, -259.15]
  }
}
