=== melobio/PrimeGen/packages/shared/src/assets/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "liquidHandlingSpecs": {
      "description": "Object containing linear equations for translating between uL of liquid and mm of plunger travel. There is one linear equation for aspiration and one for dispense",
      "type": "object",
      "required": ["aspirate", "dispense"],
      "additionalProperties": false,
      "properties": {
        "aspirate": { "$ref": "#/definitions/xyzArray" },
        "dispense": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "flowRate": {
      "description": "Object with a default value and optional dict keyed by api level. If API level is unavailable, default is used.",
      "type": "object",
      "required": ["default", "valuesByApiLevel"],
      "properties": {
        "default": {
          "$ref": "#/definitions/positiveNumber",
          "$comment": "The default value of the flowrate"
        },
        "valuesByApiLevel": { "type": "object", "required": [] }
      }
    }
  },
  "type": "object",
  "required": [
    "$otSharedSchema",
    "maxVolume",
    "minVolume",
    "defaultTipracks",
    "supportedTips",
    "defaultTipOverlapDictionary"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteLiquidPropertiesSchema.json is a reference to this schema."
    },
    "supportedTips": {
      "type": "object",
      "description": "A container of supported tip types",
      "properties": {
        "patternProperties": {
          "description": "Tip specific liquid handling properties for a given pipette. Using the active tip on a pipette, we will look up the pipetting configurations associated with that tip+pipette combo.",
          "type": "object",
          "$comment": "Example key: 't50'",
          "^t[0-9]{2,4}": {
            "required": [
              "defaultAspirateFlowRate",
              "defaultDispenseFlowRate",
              "defaultBlowOutFlowRate",
              "aspirate",
              "dispense"
            ],
            "properties": {
              "defaultAspirateFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultDispenseFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultBlowOutFlowRate": {
                "$ref": "#/definitions/flowRate"
              },
              "defaultFlowAcceleration": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultTipLength": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber"
              },
              "aspirate": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "dispense": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              }
            }
          }
        }
      }
    },
    "defaultTipOverlapDictionary": {
      "type": "object",
      "description": "Map of tip overlap values with defaults",
      "required": ["default"],
      "$comment": "Other keys in here should be labware URIs",
      "properties": {
        "default": { "type": "number" }
      },
      "additionalProperties": { "type": "number" }
    },
    "maxVolume": { "$ref": "#/definitions/positiveNumber" },
    "minVolume": { "$ref": "#/definitions/positiveNumber" },
    "defaultTipracks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/liquid/single_channel/p1000/default/2_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t1000": {
      "defaultAspirateFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultDispenseFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultBlowOutFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultTipLength": 78.3,
      "defaultReturnTipHeight": 0.83,
      "aspirate": {
        "default": {
          "1": [
            [83.6, 0.01502, 25.62],
            [90.39, 0.0152, 24.45],
            [104.1, 0.01386, 24.57],
            [117.7, 0.00991, 24.98],
            [131.3, 0.007542, 25.26],
            [158.6, 0.006723, 25.37],
            [186.1, 0.005602, 25.55],
            [199.9, 0.005013, 25.66],
            [213.6, 0.002767, 26.11],
            [241.2, 0.003594, 25.93],
            [268.6, 0.002371, 26.22],
            [323.5, 0.001687, 26.41],
            [378.3, 0.001273, 26.54],
            [433.3, 0.001039, 26.63],
            [460.8, 0.0007889, 26.74],
            [488.1, 0.0004039, 26.92],
            [515.5, 0.0005667, 26.84],
            [542.9, 0.0005983, 26.82],
            [570.4, 0.0006121, 26.81],
            [597.7, 0.0002485, 27.02],
            [625.4, 0.0008384, 26.67],
            [652.5, -0.0001662, 27.3],
            [707.4, 0.0003177, 26.98],
            [762.4, 0.000383, 26.94],
            [817.1, 0.0001665, 27.1],
            [872.1, 0.000301, 26.99],
            [927.0, 0.0002205, 27.06],
            [981.8, 0.0001571, 27.12],
            [1010.0, 0.0003381, 26.94]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [83.6, 0.01502, 25.62],
            [90.39, 0.0152, 24.45],
            [104.1, 0.01386, 24.57],
            [117.7, 0.00991, 24.98],
            [131.3, 0.007542, 25.26],
            [158.6, 0.006723, 25.37],
            [186.1, 0.005602, 25.55],
            [199.9, 0.005013, 25.66],
            [213.6, 0.002767, 26.11],
            [241.2, 0.003594, 25.93],
            [268.6, 0.002371, 26.22],
            [323.5, 0.001687, 26.41],
            [378.3, 0.001273, 26.54],
            [433.3, 0.001039, 26.63],
            [460.8, 0.0007889, 26.74],
            [488.1, 0.0004039, 26.92],
            [515.5, 0.0005667, 26.84],
            [542.9, 0.0005983, 26.82],
            [570.4, 0.0006121, 26.81],
            [597.7, 0.0002485, 27.02],
            [625.4, 0.0008384, 26.67],
            [652.5, -0.0001662, 27.3],
            [707.4, 0.0003177, 26.98],
            [762.4, 0.000383, 26.94],
            [817.1, 0.0001665, 27.1],
            [872.1, 0.000301, 26.99],
            [927.0, 0.0002205, 27.06],
            [981.8, 0.0001571, 27.12],
            [1010.0, 0.0003381, 26.94]
          ]
        }
      },
      "defaultPushOutVolume": 0
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 9.7,
    "opentrons/opentrons_96_tiprack_1000ul/1": 11.5,
    "opentrons/opentrons_96_filtertiprack_1000ul/1": 11.5,
    "opentrons/geb_96_tiprack_1000ul/1": 9.5
  },
  "maxVolume": 1000,
  "minVolume": 100.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_1000ul/1",
    "opentrons/opentrons_96_filtertiprack_1000ul/1",
    "opentrons/geb_96_tiprack_1000ul/1"
  ]
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/liquid/single_channel/p10/default/1_5.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t10": {
      "defaultAspirateFlowRate": {
        "default": 5,
        "valuesByApiLevel": { "2.0": 5 }
      },
      "defaultDispenseFlowRate": {
        "default": 10,
        "valuesByApiLevel": { "2.0": 10 }
      },
      "defaultBlowOutFlowRate": {
        "default": 1000,
        "valuesByApiLevel": { "2.0": 1000 }
      },
      "defaultTipLength": 33.0,
      "aspirate": {
        "default": {
          "1": [
            [1.553425807, -0.03427618068, 0.83],
            [1.934976526, -0.007134812859, 0.7878],
            [2.689843897, -0.007238069768, 0.788],
            [6.161165493, 0.0004663523509, 0.7673],
            [10.7963169, 0.0002200157553, 0.7688]
          ]
        }
      },
      "dispense": { "default": { "1": [[12.5135, 0.0, 0.7945]] } },
      "defaultTipOverlapDictionary": {
        "default": 3.29,
        "opentrons/opentrons_96_tiprack_10ul/1": 3.29,
        "opentrons/opentrons_96_filtertiprack_10ul/1": 3.29,
        "opentrons/geb_96_tiprack_10ul/1": 6.2,
        "opentrons/eppendorf_96_tiprack_10ul_eptips/1": 1.0
      },
      "defaultPushOutVolume": 0
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 3.29,
    "opentrons/opentrons_96_tiprack_10ul/1": 3.29,
    "opentrons/opentrons_96_filtertiprack_10ul/1": 3.29,
    "opentrons/geb_96_tiprack_10ul/1": 6.2,
    "opentrons/eppendorf_96_tiprack_10ul_eptips/1": 1.0
  },
  "maxVolume": 10,
  "minVolume": 1.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_10ul/1",
    "opentrons/opentrons_96_filtertiprack_10ul/1",
    "opentrons/geb_96_tiprack_10ul/1"
  ]
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/liquid/single_channel/p300/default/1_5.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t200": {
      "defaultAspirateFlowRate": {
        "default": 150,
        "valuesByApiLevel": { "2.0": 150 }
      },
      "defaultDispenseFlowRate": {
        "default": 300,
        "valuesByApiLevel": { "2.0": 300 }
      },
      "defaultBlowOutFlowRate": {
        "default": 1000,
        "valuesByApiLevel": { "2.0": 1000 }
      },
      "defaultTipLength": 51.7,
      "aspirate": {
        "default": {
          "1": [
            [35.11266179, 0.03721315938, 16.2497],
            [44.37338506, 0.02084320206, 16.8245],
            [63.12001468, 0.01519931266, 17.0749],
            [148.3020792, 0.005910516464, 17.6612],
            [224.5387262, 0.00227975152, 18.1997],
            [301.049323, 0.001359578667, 18.4063]
          ]
        }
      },
      "dispense": { "default": { "1": [[302.3895337, 0.0, 18.83156277]] } },
      "defaultPushOutVolume": 0
    },
    "t300": {
      "defaultAspirateFlowRate": {
        "default": 150,
        "valuesByApiLevel": { "2.0": 150 }
      },
      "defaultDispenseFlowRate": {
        "default": 300,
        "valuesByApiLevel": { "2.0": 300 }
      },
      "defaultBlowOutFlowRate": {
        "default": 1000,
        "valuesByApiLevel": { "2.0": 1000 }
      },
      "defaultTipLength": 51.7,
      "aspirate": {
        "default": {
          "1": [
            [35.11266179, 0.03721315938, 16.2497],
            [44.37338506, 0.02084320206, 16.8245],
            [63.12001468, 0.01519931266, 17.0749],
            [148.3020792, 0.005910516464, 17.6612],
            [224.5387262, 0.00227975152, 18.1997],
            [301.049323, 0.001359578667, 18.4063]
          ]
        }
      },
      "dispense": { "default": { "1": [[302.3895337, 0.0, 18.83156277]] } },
      "defaultPushOutVolume": 0
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 7.47,
    "opentrons/tipone_96_tiprack_200ul/1": 6.1,
    "opentrons/opentrons_96_filtertiprack_200ul/1": 7.47,
    "opentrons/opentrons_96_tiprack_300ul/1": 7.47
  },
  "maxVolume": 300,
  "minVolume": 30.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_300ul/1",
    "opentrons/opentrons_96_filtertiprack_200ul/1"
  ]
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/liquid/single_channel/p50/default/3_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t50": {
      "defaultAspirateFlowRate": {
        "default": 8,
        "valuesByApiLevel": { "2.14": 8 }
      },
      "defaultDispenseFlowRate": {
        "default": 8,
        "valuesByApiLevel": { "2.14": 8 }
      },
      "defaultBlowOutFlowRate": {
        "default": 4,
        "valuesByApiLevel": { "2.14": 4 }
      },
      "defaultFlowAcceleration": 1200.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.6464, 0.4817, 0.0427],
            [1.0889, 0.2539, 0.1591],
            [1.5136, 0.1624, 0.2587],
            [1.9108, 0.1042, 0.3467],
            [2.2941, 0.0719, 0.4085],
            [2.9978, 0.037, 0.4886],
            [3.7731, 0.0378, 0.4863],
            [4.7575, 0.0516, 0.4342],
            [5.5024, 0.011, 0.6275],
            [6.2686, 0.0114, 0.6253],
            [7.005, 0.0054, 0.6625],
            [8.5207, 0.0063, 0.6563],
            [10.0034, 0.003, 0.6844],
            [11.5075, 0.0031, 0.6833],
            [13.0327, 0.0032, 0.6829],
            [14.5356, 0.0018, 0.7003],
            [17.5447, 0.0014, 0.7063],
            [20.5576, 0.0011, 0.7126],
            [23.5624, 0.0007, 0.7197],
            [26.5785, 0.0007, 0.721],
            [29.593, 0.0005, 0.7248],
            [32.6109, 0.0004, 0.7268],
            [35.6384, 0.0004, 0.727],
            [38.6439, 0.0002, 0.7343],
            [41.6815, 0.0004, 0.7284],
            [44.6895, 0.0002, 0.7372],
            [47.6926, 0.0001, 0.7393],
            [51.4567, 0.0001, 0.7382]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.6464, 0.4817, 0.0427],
            [1.0889, 0.2539, 0.1591],
            [1.5136, 0.1624, 0.2587],
            [1.9108, 0.1042, 0.3467],
            [2.2941, 0.0719, 0.4085],
            [2.9978, 0.037, 0.4886],
            [3.7731, 0.0378, 0.4863],
            [4.7575, 0.0516, 0.4342],
            [5.5024, 0.011, 0.6275],
            [6.2686, 0.0114, 0.6253],
            [7.005, 0.0054, 0.6625],
            [8.5207, 0.0063, 0.6563],
            [10.0034, 0.003, 0.6844],
            [11.5075, 0.0031, 0.6833],
            [13.0327, 0.0032, 0.6829],
            [14.5356, 0.0018, 0.7003],
            [17.5447, 0.0014, 0.7063],
            [20.5576, 0.0011, 0.7126],
            [23.5624, 0.0007, 0.7197],
            [26.5785, 0.0007, 0.721],
            [29.593, 0.0005, 0.7248],
            [32.6109, 0.0004, 0.7268],
            [35.6384, 0.0004, 0.727],
            [38.6439, 0.0002, 0.7343],
            [41.6815, 0.0004, 0.7284],
            [44.6895, 0.0002, 0.7372],
            [47.6926, 0.0001, 0.7393],
            [51.4567, 0.0001, 0.7382]
          ]
        }
      },
      "defaultPushOutVolume": 2
    }
  },
  "defaultTipOverlapDictionary": {
    "default": 10.5,
    "opentrons/opentrons_flex_96_tiprack_50ul/1": 10.5
  },
  "maxVolume": 50,
  "minVolume": 5,
  "defaultTipracks": ["opentrons/opentrons_flex_96_tiprack_50ul/1"]
}

=== melobio/PrimeGen/packages/shared/src/assets/pipette/definitions/2/liquid/single_channel/p20/default/2_1.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t20": {
      "defaultAspirateFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultDispenseFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultBlowOutFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultTipLength": 31.15,
      "aspirate": {
        "opentrons/opentrons_96_tiprack_20ul/1": [
          [0.9034, 0.147, 0.6223],
          [1.0379, 0.0252, 0.6226],
          [1.1913, 0.0856, 0.5599],
          [1.3481, 0.078, 0.569],
          [1.5008, 0.0533, 0.6023],
          [1.6468, 0.0272, 0.6414],
          [1.7939, 0.0259, 0.6435],
          [1.9416, 0.0235, 0.6479],
          [2.0951, 0.0321, 0.6311],
          [2.4797, 0.0263, 0.6433],
          [2.8632, 0.0191, 0.6611],
          [3.2394, 0.0108, 0.6849],
          [3.6157, 0.0087, 0.6918],
          [3.9974, 0.0096, 0.6883],
          [4.3741, 0.0059, 0.7033],
          [4.7578, 0.0077, 0.6954],
          [5.1419, 0.0067, 0.6999],
          [5.9051, 0.0047, 0.7105],
          [7.4406, 0.0039, 0.7154],
          [8.9842, 0.003, 0.7218],
          [10.5104, 0.0014, 0.7366],
          [12.0673, 0.0022, 0.7274],
          [13.6096, 0.0012, 0.7395],
          [15.1334, 0.0004, 0.7509],
          [16.6911, 0.0013, 0.7371],
          [18.2255, 0.0005, 0.751],
          [19.7847, 0.001, 0.7412],
          [21.3395, 0.0008, 0.746]
        ],
        "default": {
          "1": [
            [0.9034, 0.147, 0.6223],
            [1.0379, 0.0252, 0.6226],
            [1.1913, 0.0856, 0.5599],
            [1.3481, 0.078, 0.569],
            [1.5008, 0.0533, 0.6023],
            [1.6468, 0.0272, 0.6414],
            [1.7939, 0.0259, 0.6435],
            [1.9416, 0.0235, 0.6479],
            [2.0951, 0.0321, 0.6311],
            [2.4797, 0.0263, 0.6433],
            [2.8632, 0.0191, 0.6611],
            [3.2394, 0.0108, 0.6849],
            [3.6157, 0.0087, 0.6918],
            [3.9974, 0.0096, 0.6883],
            [4.3741, 0.0059, 0.7033],
            [4.7578, 0.0077, 0.6954],
            [5.1419, 0.0067, 0.6999],
            [5.9051, 0.0047, 0.7105],
            [7.4406, 0.0039, 0.7154],
            [8.9842, 0.003, 0.7218],
            [10.5104, 0.0014, 0.7366],
            [12.0673, 0.0022, 0.7274],
            [13.6096, 0.0012, 0.7395],
            [15.1334, 0.0004, 0.7509],
            [16.6911, 0.0013, 0.7371],
            [18.2255, 0.0005, 0.751],
            [19.7847, 0.001, 0.7412],
            [21.3395, 0.0008, 0.746]
          ]
        }
      },
      "dispense": {
        "opentrons/opentrons_96_tiprack_20ul/1": [
          [0.9034, 0.147, 0.6223],
          [1.0379, 0.0252, 0.6226],
          [1.1913, 0.0856, 0.5599],
          [1.3481, 0.078, 0.569],
          [1.5008, 0.0533, 0.6023],
          [1.6468, 0.0272, 0.6414],
          [1.7939, 0.0259, 0.6435],
          [1.9416, 0.0235, 0.6479],
          [2.0951, 0.0321, 0.6311],
          [2.4797, 0.0263, 0.6433],
          [2.8632, 0.0191, 0.6611],
          [3.2394, 0.0108, 0.6849],
          [3.6157, 0.0087, 0.6918],
          [3.9974, 0.0096, 0.6883],
          [4.3741, 0.0059, 0.7033],
          [4.7578, 0.0077, 0.6954],
          [5.1419, 0.0067, 0.6999],
          [5.9051, 0.0047, 0.7105],
          [7.4406, 0.0039, 0.7154],
          [8.9842, 0.003, 0.7218],
          [10.5104, 0.0014, 0.7366],
          [12.0673, 0.0022, 0.7274],
          [13.6096, 0.0012, 0.7395],
          [15.1334, 0.0004, 0.7509],
          [16.6911, 0.0013, 0.7371],
          [18.2255, 0.0005, 0.751],
          [19.7847, 0.001, 0.7412],
          [21.3395, 0.0008, 0.746]
        ],
        "default": {
          "1": [
            [0.9034, 0.147, 0.6223],
            [1.0379, 0.0252, 0.6226],
            [1.1913, 0.0856, 0.5599],
            [1.3481, 0.078, 0.569],
            [1.5008, 0.0533, 0.6023],
            [1.6468, 0.0272, 0.6414],
            [1.7939, 0.0259, 0.6435],
            [1.9416, 0.0235, 0.6479],
            [2.0951, 0.0321, 0.6311],
            [2.4797, 0.0263, 0.6433],
            [2.8632, 0.0191, 0.6611],
            [3.2394, 0.0108, 0.6849],
            [3.6157, 0.0087, 0.6918],
            [3.9974, 0.0096, 0.6883],
            [4.3741, 0.0059, 0.7033],
            [4.7578, 0.0077, 0.6954],
            [5.1419, 0.0067, 0.6999],
            [5.9051, 0.0047, 0.7105],
            [7.4406, 0.0039, 0.7154],
            [8.9842, 0.003, 0.7218],
            [10.5104, 0.0014, 0.7366],
            [12.0673, 0.0022, 0.7274],
            [13.6096, 0.0012, 0.7395],
            [15.1334, 0.0004, 0.7509],
            [16.6911, 0.0013, 0.7371],
            [18.2255, 0.0005, 0.751],
            [19.7847, 0.001, 0.7412],
            [21.3395, 0.0008, 0.746]
          ]
        }
      },
      "defaultPushOutVolume": 0
    },
    "t10": {
      "defaultAspirateFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultDispenseFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultBlowOutFlowRate": {
        "default": 3.78,
        "valuesByApiLevel": { "2.0": 3.78, "2.6": 7.56 }
      },
      "defaultTipLength": 31.15,
      "aspirate": {
        "default": {
          "1": [
            [0.9034, 0.147, 0.6223],
            [1.0379, 0.0252, 0.6226],
            [1.1913, 0.0856, 0.5599],
            [1.3481, 0.078, 0.569],
            [1.5008, 0.0533, 0.6023],
            [1.6468, 0.0272, 0.6414],
            [1.7939, 0.0259, 0.6435],
            [1.9416, 0.0235, 0.6479],
            [2.0951, 0.0321, 0.6311],
            [2.4797, 0.0263, 0.6433],
            [2.8632, 0.0191, 0.6611],
            [3.2394, 0.0108, 0.6849],
            [3.6157, 0.0087, 0.6918],
            [3.9974, 0.0096, 0.6883],
            [4.3741, 0.0059, 0.7033],
            [4.7578, 0.0077, 0.6954],
            [5.1419, 0.0067, 0.6999],
            [5.9051, 0.0047, 0.7105],
            [7.4406, 0.0039, 0.7154],
            [8.9842, 0.003, 0.7218],
            [10.5104, 0.0014, 0.7366],
            [12.0673, 0.0022, 0.7274],
            [13.6096, 0.0012, 0.7395],
            [15.1334, 0.0004, 0.7509],
            [16.6911, 0.0013, 0.7371],
            [18.2255, 0.0005, 0.751],
            [19.7847, 0.001, 0.7412],
            [21.3395, 0.0008, 0.746]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.9034, 0.147, 0.6223],
            [1.0379, 0.0252, 0.6226],
            [1.1913, 0.0856, 0.5599],
            [1.3481, 0.078, 0.569],
            [1.5008, 0.0533, 0.6023],
            [1.6468, 0.0272, 0.6414],
            [1.7939, 0.0259, 0.6435],
            [1.9416, 0.0235, 0.6479],
            [2.0951, 0.0321, 0.6311],
            [2.4797, 0.0263, 0.6433],
            [2.8632, 0.0191, 0.6611],
            [3.2394, 0.0108, 0.6849],
            [3.6157, 0.0087, 0.6918],
            [3.9974, 0.0096, 0.6883],
            [4.3741, 0.0059, 0.7033],
            [4.7578, 0.0077, 0.6954],
            [5.1419, 0.0067, 0.6999],
            [5.9051, 0.0047, 0.7105],
            [7.4406, 0.0039, 0.7154],
            [8.9842, 0.003, 0.7218],
            [10.5104, 0.0014, 0.7366],
            [12.0673, 0.0022, 0.7274],
            [13.6096, 0.0012, 0.7395],
            [15.1334, 0.0004, 0.7509],
            [16.6911, 0.0013, 0.7371],
            [18.2255, 0.0005, 0.751],
            [19.7847, 0.001, 0.7412],
            [21.3395, 0.0008, 0.746]
          ]
        }
      },
      "defaultPushOutVolume": 0
    }
  },
  "maxVolume": 20,
  "minVolume": 1.0,
  "defaultTipOverlapDictionary": {
    "default": 8.25,
    "opentrons/opentrons_96_tiprack_10ul/1": 8.25,
    "opentrons/opentrons_96_filtertiprack_10ul/1": 8.25,
    "opentrons/eppendorf_96_tiprack_10ul_eptips/1": 8.4,
    "opentrons/geb_96_tiprack_10ul/1": 8.3,
    "opentrons/opentrons_96_tiprack_20ul/1": 8.25,
    "opentrons/opentrons_96_filtertiprack_20ul/1": 8.25
  },
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_20ul/1",
    "opentrons/opentrons_96_filtertiprack_20ul/1",
    "opentrons/opentrons_96_tiprack_10ul/1",
    "opentrons/opentrons_96_filtertiprack_10ul/1",
    "opentrons/geb_96_tiprack_10ul/1"
  ]
}
