=== melobio/PrimeGen/packages/shared/src/assets/labware/schemas/2.json
{
  "$id": "opentronsLabwareSchemaV2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "brandData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["brand"],
      "properties": {
        "brand": {
          "type": "string",
          "description": "Brand/manufacturer name"
        },
        "brandId": {
          "type": "array",
          "description": "An array of manufacture numbers pertaining to a given labware",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "description": "URLs for manufacturer page(s)",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "displayCategory": {
      "type": "string",
      "enum": [
        "tipRack",
        "tubeRack",
        "reservoir",
        "trash",
        "wellPlate",
        "aluminumBlock",
        "adapter",
        "other"
      ]
    },
    "safeString": {
      "description": "a string safe to use for loadName / namespace. Lowercase-only.",
      "type": "string",
      "pattern": "^[a-z0-9._]+$"
    },
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "version",
    "namespace",
    "metadata",
    "brand",
    "parameters",
    "cornerOffsetFromSlot",
    "ordering",
    "dimensions",
    "wells",
    "groups"
  ],
  "properties": {
    "schemaVersion": {
      "description": "Which schema version a labware is using",
      "type": "number",
      "enum": [2]
    },
    "version": {
      "description": "Version of the labware definition itself (eg myPlate v1/v2/v3). An incrementing integer",
      "type": "integer",
      "minimum": 1
    },
    "namespace": {
      "$ref": "#/definitions/safeString"
    },
    "metadata": {
      "type": "object",
      "description": "Properties used for search and display",
      "additionalProperties": false,
      "required": ["displayName", "displayCategory", "displayVolumeUnits"],
      "properties": {
        "displayName": {
          "description": "Easy to remember name of labware",
          "type": "string"
        },
        "displayCategory": {
          "$ref": "#/definitions/displayCategory",
          "description": "Label(s) used in UI to categorize labware"
        },
        "displayVolumeUnits": {
          "description": "Volume units for display",
          "type": "string",
          "enum": ["ÂµL", "mL", "L"]
        },
        "tags": {
          "type": "array",
          "description": "List of descriptions for a given labware",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "brand": {
      "$ref": "#/definitions/brandData",
      "description": "Real-world labware that the definition is modeled from and/or compatible with"
    },
    "parameters": {
      "type": "object",
      "description": "Internal describers used to determine pipette movement to labware",
      "additionalProperties": false,
      "required": [
        "format",
        "isTiprack",
        "loadName",
        "isMagneticModuleCompatible"
      ],
      "properties": {
        "format": {
          "description": "Property to determine compatibility with multichannel pipette",
          "type": "string",
          "enum": ["96Standard", "384Standard", "trough", "irregular", "trash"]
        },
        "quirks": {
          "description": "Property to classify a specific behavior this labware should have",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isTiprack": {
          "description": "Flag marking whether this labware is a tip rack or not",
          "type": "boolean"
        },
        "tipLength": {
          "description": "Required if this labware is a tip rack. Specifies the total length of one of this rack's tips, from top to bottom, as specified by technical drawings or as measured with calipers.",
          "$ref": "#/definitions/positiveNumber"
        },
        "tipOverlap": {
          "description": "Required if this labware is a tip rack. Specifies how far one of this rack's tips is expected to overlap with the nozzle of a pipette. In other words: tipLength, minus the distance between the bottom of the pipette and the bottom of the tip. A robot's positional calibration may fine-tune this estimate.",
          "$ref": "#/definitions/positiveNumber"
        },
        "loadName": {
          "description": "Name used to reference a labware definition",
          "$ref": "#/definitions/safeString"
        },
        "isMagneticModuleCompatible": {
          "description": "Flag marking whether a labware is compatible by default with the Magnetic Module",
          "type": "boolean"
        },
        "magneticModuleEngageHeight": {
          "description": "Distance to move magnetic module magnets to engage",
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "ordering": {
      "type": "array",
      "description": "Generated array that keeps track of how wells should be ordered in a labware",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "cornerOffsetFromSlot": {
      "type": "object",
      "additionalProperties": false,
      "description": "Distance from left-front-bottom corner of slot to left-front-bottom corner of labware bounding box. Used for labware that spans multiple slots. For labware that does not span multiple slots, x/y/z should all be zero.",
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Outer dimensions of a labware",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "yDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "zDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "xDimension": {
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "wells": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "patternProperties": {
        "[A-Z]+[0-9]+": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "shape", "totalLiquidVolume", "x", "y", "z"],
          "oneOf": [
            { "required": ["xDimension", "yDimension"] },
            { "required": ["diameter"] }
          ],
          "not": {
            "anyOf": [
              { "required": ["diameter", "xDimension"] },
              { "required": ["diameter", "yDimension"] }
            ]
          },
          "properties": {
            "depth": {
              "description": "The distance between the top and bottom of this well. If the labware is a tip rack, this will be ignored in favor of tipLength, but the values should match.",
              "$ref": "#/definitions/positiveNumber"
            },
            "x": {
              "description": "x location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "y": {
              "description": "y location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "z": {
              "description": "z location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "totalLiquidVolume": {
              "description": "Total well, tube, or tip volume in microliters",
              "$ref": "#/definitions/positiveNumber"
            },
            "xDimension": {
              "description": "x dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "yDimension": {
              "description": "y dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "diameter": {
              "description": "diameter of circular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "shape": {
              "description": "If 'rectangular', use xDimension and yDimension; if 'circular' use diameter",
              "type": "string",
              "enum": ["rectangular", "circular"]
            }
          }
        }
      }
    },
    "groups": {
      "type": "array",
      "description": "Logical well groupings for metadata/display purposes; changes in groups do not affect protocol execution",
      "items": {
        "type": "object",
        "required": ["wells", "metadata"],
        "additionalProperties": false,
        "properties": {
          "wells": {
            "type": "array",
            "description": "An array of wells that contain the same metadata",
            "items": {
              "type": "string"
            }
          },
          "metadata": {
            "type": "object",
            "description": "Metadata specific to a grid of wells in a labware",
            "required": [],
            "additionalProperties": false,
            "properties": {
              "displayName": {
                "type": "string",
                "description": "User-readable name for the well group"
              },
              "displayCategory": {
                "$ref": "#/definitions/displayCategory",
                "description": "Label(s) used in UI to categorize well groups"
              },
              "wellBottomShape": {
                "type": "string",
                "description": "Bottom shape of the well for UI purposes",
                "enum": ["flat", "u", "v"]
              }
            }
          },
          "brand": {
            "$ref": "#/definitions/brandData",
            "description": "Brand data for the well group (e.g. for tubes)"
          }
        }
      }
    },
    "allowedRoles": {
      "type": "array",
      "description": "Allowed behaviors and usage of a labware in a protocol.",
      "items": {
        "type": "string",
        "enum": ["labware", "adapter", "fixture", "maintenance"]
      }
    },
    "stackingOffsetWithLabware": {
      "type": "object",
      "description": "Supported labware that can be stacked upon, with overlap height between both labware.",
      "additionalProperties": {
        "$ref": "#/definitions/coordinates"
      }
    },
    "stackingOffsetWithModule": {
      "type": "object",
      "description": "Supported module that can be stacked upon, with overlap height between labware and module.",
      "additionalProperties": {
        "$ref": "#/definitions/coordinates"
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on this labware.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this labware."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this labware."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    },
    "gripForce": {
      "type": "number",
      "description": "Force, in Newtons, with which the gripper should grip the labware."
    },
    "gripHeightFromLabwareBottom": {
      "type": "number",
      "description": "Recommended Z-height, from labware bottom to the center of gripper pads, when gripping the labware."
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/opentrons_calibrationblock_short_side_left/1.json
{
  "wells": {
    "A1": {
      "totalLiquidVolume": 0,
      "xDimension": 63.88,
      "yDimension": 85.5,
      "shape": "rectangular",
      "depth": 0,
      "x": 31.94,
      "y": 42.75,
      "z": 33
    },
    "A2": {
      "totalLiquidVolume": 0,
      "xDimension": 63.88,
      "yDimension": 85.5,
      "shape": "rectangular",
      "depth": 0,
      "x": 95.81,
      "y": 42.75,
      "z": 62.5
    }
  },
  "groups": [
    {
      "metadata": {
        "displayName": "Opentrons Calibration Block - Short Side",
        "wellBottomShape": "flat"
      },
      "wells": ["A1"]
    },
    {
      "metadata": {
        "displayName": "Opentrons Calibration Block - Tall Side",
        "wellBottomShape": "flat"
      },
      "wells": ["A2"]
    }
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": []
  },
  "metadata": {
    "displayName": "Opentrons Calibration Block - Short Side: Left",
    "displayCategory": "aluminumBlock",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.75,
    "yDimension": 85.5,
    "zDimension": 62.5
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_calibrationblock_short_side_left"
  },
  "ordering": [["A1"], ["A2"]],
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/fixtures/2/fixture_trash.json
{
  "ordering": [["A1"]],
  "schemaVersion": 2,
  "version": 1,
  "namespace": "fixture",
  "metadata": {
    "displayCategory": "trash",
    "displayVolumeUnits": "L",
    "displayName": "Tall Fixed Trash",
    "tags": ["trash", "opentrons", "tall"]
  },
  "dimensions": {
    "xDimension": 172.86,
    "yDimension": 165.86,
    "zDimension": 82
  },
  "parameters": {
    "format": "trash",
    "isTiprack": false,
    "loadName": "fixture_trash",
    "isMagneticModuleCompatible": false,
    "quirks": ["fixedTrash", "centerMultichannelOnWells", "touchTipDisabled"]
  },
  "wells": {
    "A1": {
      "shape": "rectangular",
      "yDimension": 165.67,
      "xDimension": 107.11,
      "totalLiquidVolume": 1100000,
      "depth": 77,
      "x": 82.84,
      "y": 53.56,
      "z": 5
    }
  },
  "brand": {
    "brand": "Opentrons"
  },
  "groups": [
    {
      "wells": ["A1"],
      "metadata": {}
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap_acrylic/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": []
  },
  "metadata": {
    "displayName": "Opentrons 24 Tube Rack (Acrylic) with Eppendorf 2 mL Safe-Lock Snapcap",
    "displayCategory": "tubeRack",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.48,
    "zDimension": 52
  },
  "wells": {
    "D1": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 15.28,
      "y": 13.9,
      "z": 13.42
    },
    "C1": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 15.28,
      "y": 33.4,
      "z": 13.42
    },
    "B1": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 15.28,
      "y": 52.9,
      "z": 13.42
    },
    "A1": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 15.28,
      "y": 72.4,
      "z": 13.42
    },
    "D2": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 34.78,
      "y": 13.9,
      "z": 13.42
    },
    "C2": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 34.78,
      "y": 33.4,
      "z": 13.42
    },
    "B2": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 34.78,
      "y": 52.9,
      "z": 13.42
    },
    "A2": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 34.78,
      "y": 72.4,
      "z": 13.42
    },
    "D3": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 54.28,
      "y": 13.9,
      "z": 13.42
    },
    "C3": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 54.28,
      "y": 33.4,
      "z": 13.42
    },
    "B3": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 54.28,
      "y": 52.9,
      "z": 13.42
    },
    "A3": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 54.28,
      "y": 72.4,
      "z": 13.42
    },
    "D4": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 73.78,
      "y": 13.9,
      "z": 13.42
    },
    "C4": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 73.78,
      "y": 33.4,
      "z": 13.42
    },
    "B4": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 73.78,
      "y": 52.9,
      "z": 13.42
    },
    "A4": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 73.78,
      "y": 72.4,
      "z": 13.42
    },
    "D5": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 93.28,
      "y": 13.9,
      "z": 13.42
    },
    "C5": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 93.28,
      "y": 33.4,
      "z": 13.42
    },
    "B5": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 93.28,
      "y": 52.9,
      "z": 13.42
    },
    "A5": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 93.28,
      "y": 72.4,
      "z": 13.42
    },
    "D6": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 112.78,
      "y": 13.9,
      "z": 13.42
    },
    "C6": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 112.78,
      "y": 33.4,
      "z": 13.42
    },
    "B6": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 112.78,
      "y": 52.9,
      "z": 13.42
    },
    "A6": {
      "depth": 38.58,
      "shape": "circular",
      "diameter": 9.9,
      "totalLiquidVolume": 2000,
      "x": 112.78,
      "y": 72.4,
      "z": 13.42
    }
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap_acrylic"
  },
  "groups": [
    {
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ],
      "metadata": {
        "displayName": "Eppendorf 24x2 mL Safelock Snapcap",
        "displayCategory": "tubeRack",
        "wellBottomShape": "u"
      },
      "brand": {
        "brand": "Eppendorf",
        "brandId": [
          "022363344",
          "022363352",
          "022363379",
          "022363395",
          "022363417",
          "022363433",
          "022363450",
          "022363476"
        ],
        "links": [
          "https://online-shop.eppendorf.us/US-en/Laboratory-Consumables-44512/Tubes-44515/Eppendorf-Safe-Lock-Tubes-PF-8863.html"
        ]
      }
    }
  ],
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/opentrons_24_tuberack_generic_2ml_screwcap/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "schemaVersion": 2,
  "version": 1,
  "namespace": "opentrons",
  "metadata": {
    "displayVolumeUnits": "mL",
    "displayCategory": "tubeRack",
    "displayName": "Opentrons 24 Tube Rack with Generic 2 mL Screwcap",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.75,
    "yDimension": 85.5,
    "zDimension": 84
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "loadName": "opentrons_24_tuberack_generic_2ml_screwcap",
    "isMagneticModuleCompatible": false
  },
  "wells": {
    "D1": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 17.59,
      "z": 42
    },
    "C1": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 36.87,
      "z": 42
    },
    "B1": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 56.15,
      "z": 42
    },
    "A1": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 75.43,
      "z": 42
    },
    "D2": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 17.59,
      "z": 42
    },
    "C2": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 36.87,
      "z": 42
    },
    "B2": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 56.15,
      "z": 42
    },
    "A2": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 75.43,
      "z": 42
    },
    "D3": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 17.59,
      "z": 42
    },
    "C3": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 36.87,
      "z": 42
    },
    "B3": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 56.15,
      "z": 42
    },
    "A3": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 75.43,
      "z": 42
    },
    "D4": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 17.59,
      "z": 42
    },
    "C4": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 36.87,
      "z": 42
    },
    "B4": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 56.15,
      "z": 42
    },
    "A4": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 75.43,
      "z": 42
    },
    "D5": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 17.59,
      "z": 42
    },
    "C5": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 36.87,
      "z": 42
    },
    "B5": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 56.15,
      "z": 42
    },
    "A5": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 75.43,
      "z": 42
    },
    "D6": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 17.59,
      "z": 42
    },
    "C6": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 36.87,
      "z": 42
    },
    "B6": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 56.15,
      "z": 42
    },
    "A6": {
      "depth": 42,
      "diameter": 8.5,
      "shape": "circular",
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 75.43,
      "z": 42
    }
  },
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": [
      "https://shop.opentrons.com/collections/opentrons-tips/products/tube-rack-set-1"
    ]
  },
  "groups": [
    {
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ],
      "metadata": {
        "displayName": "Generic 2 mL Screwcap",
        "displayCategory": "tubeRack",
        "wellBottomShape": "v"
      },
      "brand": {
        "brand": "generic",
        "brandId": [],
        "links": []
      }
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}
