=== melobio/PrimeGen/packages/shared/src/assets/labware/schemas/2.json
{
  "$id": "opentronsLabwareSchemaV2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "brandData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["brand"],
      "properties": {
        "brand": {
          "type": "string",
          "description": "Brand/manufacturer name"
        },
        "brandId": {
          "type": "array",
          "description": "An array of manufacture numbers pertaining to a given labware",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "description": "URLs for manufacturer page(s)",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "displayCategory": {
      "type": "string",
      "enum": [
        "tipRack",
        "tubeRack",
        "reservoir",
        "trash",
        "wellPlate",
        "aluminumBlock",
        "adapter",
        "other"
      ]
    },
    "safeString": {
      "description": "a string safe to use for loadName / namespace. Lowercase-only.",
      "type": "string",
      "pattern": "^[a-z0-9._]+$"
    },
    "coordinates": {
      "type": "object",
      "additionalProperties": false,
      "required": ["x", "y", "z"],
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      }
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "version",
    "namespace",
    "metadata",
    "brand",
    "parameters",
    "cornerOffsetFromSlot",
    "ordering",
    "dimensions",
    "wells",
    "groups"
  ],
  "properties": {
    "schemaVersion": {
      "description": "Which schema version a labware is using",
      "type": "number",
      "enum": [2]
    },
    "version": {
      "description": "Version of the labware definition itself (eg myPlate v1/v2/v3). An incrementing integer",
      "type": "integer",
      "minimum": 1
    },
    "namespace": {
      "$ref": "#/definitions/safeString"
    },
    "metadata": {
      "type": "object",
      "description": "Properties used for search and display",
      "additionalProperties": false,
      "required": ["displayName", "displayCategory", "displayVolumeUnits"],
      "properties": {
        "displayName": {
          "description": "Easy to remember name of labware",
          "type": "string"
        },
        "displayCategory": {
          "$ref": "#/definitions/displayCategory",
          "description": "Label(s) used in UI to categorize labware"
        },
        "displayVolumeUnits": {
          "description": "Volume units for display",
          "type": "string",
          "enum": ["ÂµL", "mL", "L"]
        },
        "tags": {
          "type": "array",
          "description": "List of descriptions for a given labware",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "brand": {
      "$ref": "#/definitions/brandData",
      "description": "Real-world labware that the definition is modeled from and/or compatible with"
    },
    "parameters": {
      "type": "object",
      "description": "Internal describers used to determine pipette movement to labware",
      "additionalProperties": false,
      "required": [
        "format",
        "isTiprack",
        "loadName",
        "isMagneticModuleCompatible"
      ],
      "properties": {
        "format": {
          "description": "Property to determine compatibility with multichannel pipette",
          "type": "string",
          "enum": ["96Standard", "384Standard", "trough", "irregular", "trash"]
        },
        "quirks": {
          "description": "Property to classify a specific behavior this labware should have",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isTiprack": {
          "description": "Flag marking whether this labware is a tip rack or not",
          "type": "boolean"
        },
        "tipLength": {
          "description": "Required if this labware is a tip rack. Specifies the total length of one of this rack's tips, from top to bottom, as specified by technical drawings or as measured with calipers.",
          "$ref": "#/definitions/positiveNumber"
        },
        "tipOverlap": {
          "description": "Required if this labware is a tip rack. Specifies how far one of this rack's tips is expected to overlap with the nozzle of a pipette. In other words: tipLength, minus the distance between the bottom of the pipette and the bottom of the tip. A robot's positional calibration may fine-tune this estimate.",
          "$ref": "#/definitions/positiveNumber"
        },
        "loadName": {
          "description": "Name used to reference a labware definition",
          "$ref": "#/definitions/safeString"
        },
        "isMagneticModuleCompatible": {
          "description": "Flag marking whether a labware is compatible by default with the Magnetic Module",
          "type": "boolean"
        },
        "magneticModuleEngageHeight": {
          "description": "Distance to move magnetic module magnets to engage",
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "ordering": {
      "type": "array",
      "description": "Generated array that keeps track of how wells should be ordered in a labware",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "cornerOffsetFromSlot": {
      "type": "object",
      "additionalProperties": false,
      "description": "Distance from left-front-bottom corner of slot to left-front-bottom corner of labware bounding box. Used for labware that spans multiple slots. For labware that does not span multiple slots, x/y/z should all be zero.",
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Outer dimensions of a labware",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "yDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "zDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "xDimension": {
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "wells": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "patternProperties": {
        "[A-Z]+[0-9]+": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "shape", "totalLiquidVolume", "x", "y", "z"],
          "oneOf": [
            { "required": ["xDimension", "yDimension"] },
            { "required": ["diameter"] }
          ],
          "not": {
            "anyOf": [
              { "required": ["diameter", "xDimension"] },
              { "required": ["diameter", "yDimension"] }
            ]
          },
          "properties": {
            "depth": {
              "description": "The distance between the top and bottom of this well. If the labware is a tip rack, this will be ignored in favor of tipLength, but the values should match.",
              "$ref": "#/definitions/positiveNumber"
            },
            "x": {
              "description": "x location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "y": {
              "description": "y location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "z": {
              "description": "z location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "totalLiquidVolume": {
              "description": "Total well, tube, or tip volume in microliters",
              "$ref": "#/definitions/positiveNumber"
            },
            "xDimension": {
              "description": "x dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "yDimension": {
              "description": "y dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "diameter": {
              "description": "diameter of circular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "shape": {
              "description": "If 'rectangular', use xDimension and yDimension; if 'circular' use diameter",
              "type": "string",
              "enum": ["rectangular", "circular"]
            }
          }
        }
      }
    },
    "groups": {
      "type": "array",
      "description": "Logical well groupings for metadata/display purposes; changes in groups do not affect protocol execution",
      "items": {
        "type": "object",
        "required": ["wells", "metadata"],
        "additionalProperties": false,
        "properties": {
          "wells": {
            "type": "array",
            "description": "An array of wells that contain the same metadata",
            "items": {
              "type": "string"
            }
          },
          "metadata": {
            "type": "object",
            "description": "Metadata specific to a grid of wells in a labware",
            "required": [],
            "additionalProperties": false,
            "properties": {
              "displayName": {
                "type": "string",
                "description": "User-readable name for the well group"
              },
              "displayCategory": {
                "$ref": "#/definitions/displayCategory",
                "description": "Label(s) used in UI to categorize well groups"
              },
              "wellBottomShape": {
                "type": "string",
                "description": "Bottom shape of the well for UI purposes",
                "enum": ["flat", "u", "v"]
              }
            }
          },
          "brand": {
            "$ref": "#/definitions/brandData",
            "description": "Brand data for the well group (e.g. for tubes)"
          }
        }
      }
    },
    "allowedRoles": {
      "type": "array",
      "description": "Allowed behaviors and usage of a labware in a protocol.",
      "items": {
        "type": "string",
        "enum": ["labware", "adapter", "fixture", "maintenance"]
      }
    },
    "stackingOffsetWithLabware": {
      "type": "object",
      "description": "Supported labware that can be stacked upon, with overlap height between both labware.",
      "additionalProperties": {
        "$ref": "#/definitions/coordinates"
      }
    },
    "stackingOffsetWithModule": {
      "type": "object",
      "description": "Supported module that can be stacked upon, with overlap height between labware and module.",
      "additionalProperties": {
        "$ref": "#/definitions/coordinates"
      }
    },
    "gripperOffsets": {
      "type": "object",
      "description": "Offsets to be added when calculating the coordinates a gripper should go to when picking up or dropping a labware on this labware.",
      "properties": {
        "default": {
          "type": "object",
          "properties": {
            "pickUpOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate pick-up coordinates of a labware placed on this labware."
            },
            "dropOffset": {
              "$ref": "#/definitions/coordinates",
              "description": "Offset added to calculate drop coordinates of a labware placed on this labware."
            }
          },
          "required": ["pickUpOffset", "dropOffset"]
        }
      },
      "required": ["default"]
    },
    "gripForce": {
      "type": "number",
      "description": "Force, in Newtons, with which the gripper should grip the labware."
    },
    "gripHeightFromLabwareBottom": {
      "type": "number",
      "description": "Recommended Z-height, from labware bottom to the center of gripper pads, when gripping the labware."
    }
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/opentrons_24_tuberack_nest_1.5ml_snapcap/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": [
      "https://shop.opentrons.com/collections/opentrons-tips/products/tube-rack-set-1"
    ]
  },
  "metadata": {
    "displayName": "Opentrons 24 Tube Rack with NEST 1.5 mL Snapcap",
    "displayCategory": "tubeRack",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.75,
    "yDimension": 85.5,
    "zDimension": 79.55
  },
  "wells": {
    "A1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 18.21,
      "y": 75.43,
      "z": 41.65
    },
    "B1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 18.21,
      "y": 56.15,
      "z": 41.65
    },
    "C1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 18.21,
      "y": 36.87,
      "z": 41.65
    },
    "D1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 18.21,
      "y": 17.59,
      "z": 41.65
    },
    "A2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38.1,
      "y": 75.43,
      "z": 41.65
    },
    "B2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38.1,
      "y": 56.15,
      "z": 41.65
    },
    "C2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38.1,
      "y": 36.87,
      "z": 41.65
    },
    "D2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38.1,
      "y": 17.59,
      "z": 41.65
    },
    "A3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 57.99,
      "y": 75.43,
      "z": 41.65
    },
    "B3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 57.99,
      "y": 56.15,
      "z": 41.65
    },
    "C3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 57.99,
      "y": 36.87,
      "z": 41.65
    },
    "D3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 57.99,
      "y": 17.59,
      "z": 41.65
    },
    "A4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 77.88,
      "y": 75.43,
      "z": 41.65
    },
    "B4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 77.88,
      "y": 56.15,
      "z": 41.65
    },
    "C4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 77.88,
      "y": 36.87,
      "z": 41.65
    },
    "D4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 77.88,
      "y": 17.59,
      "z": 41.65
    },
    "A5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 97.77,
      "y": 75.43,
      "z": 41.65
    },
    "B5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 97.77,
      "y": 56.15,
      "z": 41.65
    },
    "C5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 97.77,
      "y": 36.87,
      "z": 41.65
    },
    "D5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 97.77,
      "y": 17.59,
      "z": 41.65
    },
    "A6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 117.66,
      "y": 75.43,
      "z": 41.65
    },
    "B6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 117.66,
      "y": 56.15,
      "z": 41.65
    },
    "C6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 117.66,
      "y": 36.87,
      "z": 41.65
    },
    "D6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 117.66,
      "y": 17.59,
      "z": 41.65
    }
  },
  "groups": [
    {
      "metadata": {
        "displayName": "NEST 24x1.5 mL Snapcap",
        "displayCategory": "tubeRack",
        "wellBottomShape": "v"
      },
      "brand": {
        "brand": "NEST",
        "brandId": ["615601", "615001"],
        "links": [
          "https://www.nest-biotech.com/micro-centrifuge-tube/59201044.html"
        ]
      },
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ]
    }
  ],
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_24_tuberack_nest_1.5ml_snapcap"
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/corning_24_wellplate_3.4ml_flat/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "brand": {
    "brand": "Corning",
    "brandId": ["3337", "3524", "3526", "3527", "3473", "3738", "3987"],
    "links": [
      "https://ecatalog.corning.com/life-sciences/b2c/US/en/Microplates/Assay-Microplates/96-Well-Microplates/Costar%C2%AE-Multiple-Well-Cell-Culture-Plates/p/3738"
    ]
  },
  "schemaVersion": 2,
  "version": 1,
  "namespace": "opentrons",
  "metadata": {
    "displayName": "Corning 24 Well Plate 3.4 mL Flat",
    "displayVolumeUnits": "mL",
    "displayCategory": "wellPlate",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.47,
    "zDimension": 20.27
  },
  "wells": {
    "D1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 17.48,
      "y": 13.77,
      "z": 2.87
    },
    "C1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 17.48,
      "y": 33.07,
      "z": 2.87
    },
    "B1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 17.48,
      "y": 52.37,
      "z": 2.87
    },
    "A1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 17.48,
      "y": 71.67,
      "z": 2.87
    },
    "D2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 36.78,
      "y": 13.77,
      "z": 2.87
    },
    "C2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 36.78,
      "y": 33.07,
      "z": 2.87
    },
    "B2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 36.78,
      "y": 52.37,
      "z": 2.87
    },
    "A2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 36.78,
      "y": 71.67,
      "z": 2.87
    },
    "D3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 56.08,
      "y": 13.77,
      "z": 2.87
    },
    "C3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 56.08,
      "y": 33.07,
      "z": 2.87
    },
    "B3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 56.08,
      "y": 52.37,
      "z": 2.87
    },
    "A3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 56.08,
      "y": 71.67,
      "z": 2.87
    },
    "D4": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 75.38,
      "y": 13.77,
      "z": 2.87
    },
    "C4": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 75.38,
      "y": 33.07,
      "z": 2.87
    },
    "B4": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 75.38,
      "y": 52.37,
      "z": 2.87
    },
    "A4": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 75.38,
      "y": 71.67,
      "z": 2.87
    },
    "D5": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 94.68,
      "y": 13.77,
      "z": 2.87
    },
    "C5": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 94.68,
      "y": 33.07,
      "z": 2.87
    },
    "B5": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 94.68,
      "y": 52.37,
      "z": 2.87
    },
    "A5": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 94.68,
      "y": 71.67,
      "z": 2.87
    },
    "D6": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 113.98,
      "y": 13.77,
      "z": 2.87
    },
    "C6": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 113.98,
      "y": 33.07,
      "z": 2.87
    },
    "B6": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 113.98,
      "y": 52.37,
      "z": 2.87
    },
    "A6": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 16.26,
      "totalLiquidVolume": 3400,
      "x": 113.98,
      "y": 71.67,
      "z": 2.87
    }
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "corning_24_wellplate_3.4ml_flat"
  },
  "groups": [
    {
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ],
      "metadata": {
        "wellBottomShape": "flat"
      }
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/axygen_1_reservoir_90ml/1.json
{
  "ordering": [["A1"]],
  "brand": {
    "brand": "Axygen",
    "brandId": ["RES-SW1-LP"],
    "links": [
      "https://ecatalog.corning.com/life-sciences/b2c/US/en/Genomics-%26-Molecular-Biology/Automation-Consumables/Automation-Reservoirs/Axygen%C2%AE-Reagent-Reservoirs/p/RES-SW1-LP?clear=true"
    ]
  },
  "metadata": {
    "displayName": "Axygen 1 Well Reservoir 90 mL",
    "displayCategory": "reservoir",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.47,
    "zDimension": 19.05
  },
  "wells": {
    "A1": {
      "depth": 12.42,
      "shape": "rectangular",
      "xDimension": 106.76,
      "yDimension": 70.52,
      "totalLiquidVolume": 90000,
      "x": 63.88,
      "y": 42.735,
      "z": 6.63
    }
  },
  "groups": [
    {
      "wells": ["A1"],
      "metadata": {
        "wellBottomShape": "flat"
      }
    }
  ],
  "parameters": {
    "format": "trough",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "axygen_1_reservoir_90ml",
    "quirks": ["centerMultichannelOnWells", "touchTipDisabled"]
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/nest_1_reservoir_290ml/1.json
{
  "ordering": [["A1"]],
  "brand": {
    "brand": "NEST",
    "brandId": ["360206", "360266"],
    "links": ["https://www.nest-biotech.com/reagent-reserviors"]
  },
  "metadata": {
    "displayName": "NEST 1 Well Reservoir 290 mL",
    "displayCategory": "reservoir",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.47,
    "zDimension": 44.4
  },
  "wells": {
    "A1": {
      "depth": 39.55,
      "shape": "rectangular",
      "xDimension": 106.8,
      "yDimension": 71.2,
      "totalLiquidVolume": 290000,
      "x": 63.88,
      "y": 42.74,
      "z": 4.85
    }
  },
  "groups": [
    {
      "metadata": {
        "wellBottomShape": "v"
      },
      "wells": ["A1"]
    }
  ],
  "parameters": {
    "format": "trough",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "quirks": ["centerMultichannelOnWells", "touchTipDisabled"],
    "loadName": "nest_1_reservoir_290ml"
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== melobio/PrimeGen/packages/shared/src/assets/labware/definitions/2/opentrons_1_trash_1100ml_fixed/1.json
{
  "ordering": [["A1"]],
  "metadata": {
    "displayCategory": "trash",
    "displayVolumeUnits": "mL",
    "displayName": "Opentrons Fixed Trash",
    "tags": []
  },
  "schemaVersion": 2,
  "version": 1,
  "namespace": "opentrons",
  "dimensions": {
    "xDimension": 172.86,
    "yDimension": 165.86,
    "zDimension": 82
  },
  "parameters": {
    "format": "trash",
    "isTiprack": false,
    "loadName": "opentrons_1_trash_1100ml_fixed",
    "isMagneticModuleCompatible": false,
    "quirks": ["fixedTrash", "centerMultichannelOnWells", "touchTipDisabled"]
  },
  "wells": {
    "A1": {
      "shape": "rectangular",
      "yDimension": 165.67,
      "xDimension": 107.11,
      "totalLiquidVolume": 1100000,
      "depth": 0,
      "x": 82.84,
      "y": 80,
      "z": 82
    }
  },
  "brand": {
    "brand": "Opentrons"
  },
  "groups": [
    {
      "wells": ["A1"],
      "metadata": {}
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}
